# Generated by Django 3.2.5 on 2021-07-17 20:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ImageModel',
            fields=[
                ('image_id', models.IntegerField(primary_key=True, serialize=False)),
                ('image_url', models.URLField(blank=True, verbose_name='Ссылка')),
                ('image_loc', models.ImageField(blank=True, upload_to='images/', verbose_name='Файл')),
                ('width_origin', models.PositiveIntegerField(default=200, verbose_name='Ширина')),
                ('height_origin', models.PositiveIntegerField(default=200, verbose_name='Высота')),
            ],
        ),
        migrations.CreateModel(
            name='ImageUpdate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('width', models.PositiveIntegerField(blank=True, verbose_name='Ширина')),
                ('height', models.PositiveIntegerField(blank=True, verbose_name='Высота')),
                ('parent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='modified', to='img_app.imagemodel')),
            ],
        ),
    ]
