# Generated by Django 3.2.5 on 2021-07-15 05:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('img_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ImageModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('image_url', models.URLField(blank=True, verbose_name='Ссылка')),
                ('image_loc', models.ImageField(blank=True, upload_to='images/', verbose_name='Файл')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Опубликовано')),
                ('width_origin', models.PositiveIntegerField(blank=True, verbose_name='Ширина')),
                ('height_origin', models.PositiveIntegerField(blank=True, verbose_name='Высота')),
            ],
        ),
        migrations.DeleteModel(
            name='Image',
        ),
    ]
