# Generated by Django 3.2.5 on 2021-07-13 11:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('img_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='image',
            name='image_url',
            field=models.FileField(blank=True, upload_to='images/', verbose_name='Ссылка'),
        ),
    ]
