# Generated by Django 3.2.5 on 2021-07-13 20:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('img_app', '0002_alter_image_image_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='image',
            name='image_loc',
            field=models.ImageField(upload_to='images/', verbose_name='Файл'),
        ),
        migrations.AlterField(
            model_name='image',
            name='image_url',
            field=models.URLField(verbose_name='Ссылка'),
        ),
    ]
