# Generated by Django 3.2.5 on 2021-07-15 05:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('img_app', '0002_auto_20210715_0833'),
    ]

    operations = [
        migrations.AlterField(
            model_name='imagemodel',
            name='height_origin',
            field=models.PositiveIntegerField(verbose_name='Высота'),
        ),
        migrations.AlterField(
            model_name='imagemodel',
            name='width_origin',
            field=models.PositiveIntegerField(verbose_name='Ширина'),
        ),
    ]
