# Generated by Django 3.2.5 on 2021-07-13 20:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('img_app', '0003_auto_20210713_2318'),
    ]

    operations = [
        migrations.AlterField(
            model_name='image',
            name='image_url',
            field=models.URLField(blank=True, verbose_name='Ссылка'),
        ),
    ]
