# Generated by Django 3.2.5 on 2021-07-15 05:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('img_app', '0003_auto_20210715_0837'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='imagemodel',
            name='height_origin',
        ),
        migrations.RemoveField(
            model_name='imagemodel',
            name='width_origin',
        ),
    ]
