# Generated by Django 3.2.5 on 2021-07-15 06:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('img_app', '0004_auto_20210715_0842'),
    ]

    operations = [
        migrations.AddField(
            model_name='imagemodel',
            name='image_file',
            field=models.ImageField(blank=True, upload_to='images/'),
        ),
    ]
