# Generated by Django 3.2.5 on 2021-07-15 07:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('img_app', '0005_imagemodel_image_file'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='imagemodel',
            name='image_file',
        ),
    ]
